### PR TITLE
ElDoc support

### PR DESCRIPTION
**Pull request by X4lldux**
Displaying argument lists via ElDoc, based on doc strings.

### CODE REVIEW

**Comment by tonini** [comment]
@X4lldux as we talk about it I will label this PR as `onhold` until I'm done with the implementation of the `alchemist-server` functionality to get detailed `Module/function` informations. 

Thanks

**Comment by malchmih** [comment]
Eldoc support would be great :+1:

**Comment by X4lldux** [comment]
Yeah, but alchemist's server code changed so much that I have write it from start. I'll make a new pull request when I'll find time for it.

**Comment by erikbye** [comment]
Any current plans for implementing Eldoc support?

**Pull request closed without merging**
