### PR TITLE
Revert revert of pr #62

### PR DESCRIPTION
**Pull request by rranelli**
As I've said in #61, reverting #62 was not necessary.

This PR reverts the revert of PR #62.

Since my PR at #61 kinda conflicts with #62, I would rather have the contents of #62 in master first before patching a replacement for #61.

I've tested the menu locally and everything seems to work fine.

/cc @tonini @jtmoulia

### CODE REVIEW

**Comment by jtmoulia** [comment]
Took me awhile to catch up, but makes sense -- thanks @rranelli for the fix and PR juggling!

**Comment by tonini** [comment]
great! :D thanks

PS: Sorry for don't be active enough, having kind of a rough time at the moment. Thanks for understanding.

**Comment by jtmoulia** [comment]
No worries @tonini, but consider giving @rranelli commit rights.

**Comment by rranelli** [comment]
@tonini No problem! Hope stuff gets better soon.

**Pull request merged**
