### PR TITLE
Fix literal TAB binding to company-complete

### PR DESCRIPTION
**Pull request by walter**
See issue #258 

Credit due those mentioned in issue as well Elixir team on Slack's #emacs channel.

### CODE REVIEW

**Comment by syohex** [comment]
It should be `(kbd "TAB")` as below.

https://github.com/emacs-mirror/emacs/blob/48079f68125e75cf581ef2b86b00c5a3851dd6e7/lisp/net/rcirc.el#L978

**Comment by walter** [comment]
Amended, thanks @syohex!

**Comment by tonini** [comment]
Hi @walter 

As @syohex mentioned it should be `(kbd "TAB")`. This is all my fault. 😏 

Could you please update the `PR` so we could fix this thing. 👍

**Comment by walter** [comment]
@tonini force pushed amended commit. Should be good to go.

**Comment by tonini** [comment]
Great! Thanks a lot 👍

**Pull request merged**
