### PR TITLE
jump to function/macro definitions inside current file

### PR DESCRIPTION
**Pull request by tonini**

### CODE REVIEW

**Comment by tonini** [comment]
We need to update the imenu expression regex also

https://github.com/elixir-lang/emacs-elixir/pull/213

**Comment by larshesel** [comment]
Tested this just 10 mins ago and it works great! :+1:

**Comment by larshesel** [comment]
just checked the speed improvements, fantastic!

**Comment by tonini** [comment]
fixes #83

**Comment by tonini** [comment]
@larshesel as always, thanks for help! :heart: :smile: :green_heart:

**Pull request merged**
