### PR TITLE
Add alchemist-company backend correctly.

### PR DESCRIPTION
**Pull request by stardiviner**
Solve this issue:

https://github.com/tonini/alchemist.el/issues/244

### CODE REVIEW

**Comment by tonini** [comment]
Hi @stardiviner 

Thanks for the contribution. I tested it but the completion won't work anymore with it. Did you tried it manually by yourself?

**Comment by stardiviner** [comment]
I have not tested it. This code is the usually way to add a company-mode backend. But really should not add it globally.

I think the PR should work. Can you show me your value of `company-backends` in `elixir-mode` buffer?

**Comment by tonini** [comment]
@stardiviner Hey

I see your point and the recommendation about how to add the alchemist-backend is absolutely the way to go. But until we're sure that it will work I can merge the PR. 

As you can see here: https://github.com/tonini/emacs.d/blob/b4c8e74450d3fed964201c702b2843c5c75b9421/init.el#L203 I have no special `company-mode` setup. So please, test your `PR` in the wild too.

**Comment by stardiviner** [comment]
@tonini Hey, can you test in your environment by the following steps?

1. check whether company-mode is active?
2. show my the `company-backends` value
3. show the result of `company-diag` in code completion.

Because I tested in my .emacs, and `emacs -q`.
Both works.
And I also did a test:

```org
#+BEGIN_SRC emacs-lisp :results output
(setq my-company-backends
      '(company-files
        (company-capf
         :with
         company-yasnippet)
        company-dabbrev-code
        company-abbrev
        company-keywords
        ))

(print my-company-backends)

(add-to-list (make-local-variable 'my-company-backends) 'alchemist-company)

(print my-company-backends)
#+END_SRC

#+RESULTS:
: 
: (company-files (company-capf :with company-yasnippet) company-dabbrev-code company-abbrev company-keywords)
: 
: (alchemist-company company-files (company-capf :with company-yasnippet) company-dabbrev-code company-abbrev company-keywords)
```
You can see, it works exactly as expected.
Maybe because `(company-mode)` in my patch disabled `company-mode` in `alchemist-mode` buffer.

**Comment by tonini** [comment]
@stardiviner I tested it and it works like a charm. 👍 

Could you please squash the commits to just one so we can merge this `PR`. 😏

**Comment by whatyouhide** [comment]
Just chiming in to say that you can squash commits when merging the PR now @tonini, there's a dropdown on the "Merge pull request" option so you can squash the commits yourself and write message and such yourself (it will say "X committed with @tonini") :)

**Comment by tonini** [comment]
@whatyouhide omg! haha how cool is that :D Grazie! 😄

**Comment by stardiviner** [comment]
Great. Thanks.

**Comment by tonini** [comment]
@stardiviner Thanks a lot for the contribution and teaching me how to adding custom company backends the proper way. ❤️ 💛 💙 💚 😏

**Comment by stardiviner** [comment]
@tonini my bad that have not thought might company-mode is disabled by my code.

**Pull request merged**
