### PR TITLE
Company mode api usage

### PR DESCRIPTION
**Pull request by tonini**
@rranelli Thats a great catch! :+1: 

I added your changes about adding the `alchemist-backed` just locally and that's a really good catch. :)

The second thing is that the changes about making the keybindings local didn't work, so I read a bit of the `company-mode` source and found the solution.

You can see all it does is using the interface and proper functions from company-mode to call alchemist's specific functions.

Do you think thats a good move? You could test it and give me an ok afterwards.

### CODE REVIEW

**Comment by tonini** [comment]
fixes #99

**Comment by rranelli** [comment]
I know little about company, but this seems like the right way to go, specially when something [like this](https://github.com/tonini/alchemist.el/pull/100/files#diff-236a3a4364f49809833f502749ea65b0R70) is used instead.

I've the changes over here and everything seems fine. Nice work :+1:

**Comment by tonini** [comment]
Great! Thanks for the awesome catch! :) :heart: :yellow_heart: :green_heart:

**Comment by rranelli** [comment]
always happy to help o/

**Pull request merged**
